"""add table email & created_at on send_emails

Revision ID: 7aee6b3c47a3
Revises: efad61d609cb
Create Date: 2024-07-14 18:21:09.921468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aee6b3c47a3'
down_revision = 'efad61d609cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_emails', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('email')
    # ### end Alembic commands ###
