"""add relation on recipient_emails

Revision ID: bd7cb053d1a9
Revises: b909d38ed3d5
Create Date: 2024-07-14 18:56:48.840076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7cb053d1a9'
down_revision = 'b909d38ed3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_emails_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'send_emails', ['send_emails_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient_emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('send_emails_id')

    # ### end Alembic commands ###
