"""first initial & tabel send_email

Revision ID: ce7d3da5aac3
Revises: 
Create Date: 2024-07-14 12:18:12.734844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7d3da5aac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_emails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('email_subject', sa.String(length=120), nullable=True),
    sa.Column('email_content', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('send_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_emails')
    # ### end Alembic commands ###
