"""add celery id

Revision ID: efad61d609cb
Revises: ce7d3da5aac3
Create Date: 2024-07-14 15:49:43.117141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad61d609cb'
down_revision = 'ce7d3da5aac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_emails', schema=None) as batch_op:
        batch_op.drop_column('celery_id')

    # ### end Alembic commands ###
